### PR TITLE
feat: ucore/packages.json: Add NetworkManager-wifi

### PR DESCRIPTION
**Pull request by travier**
Add NetworkManager-wifi for a better wifi management experience.

---

Based on https://github.com/ublue-os/ucore/pull/139 for convenience.

See: https://github.com/ublue-os/ucore/issues/138
See: https://github.com/coreos/fedora-coreos-tracker/issues/862

### CODE REVIEW

**Comment by bsherman** [comment]
There was also a comment about adding `iwd` on the issue which spawned this PR: https://github.com/ublue-os/ucore/issues/138#issuecomment-2035244506 .

I'd like to get feedback from some users of `ucore` before we proceed with adding either `NetworkManager-wifi` or `iwd` to `ucore`. If we do add `iwd`, I want it to be added at the same time as `NetworkManager-wifi`.

**Comment by travier** [comment]
I *think* it's independent. You would want `NetworkManager-wifi` in all cases to manage wifi devices using NetworkManager.

**Comment by bsherman** [comment]
> I _think_ it's independent. You would want `NetworkManager-wifi` in all cases to manage wifi devices using NetworkManager.

Agreed using `NetworkManager-wifi` to manage is preferred. 

The reason I'm linking them is if a user first runs `wpa_supplicant` as the `NetworkManager-wifi` backend, the PSK for a given SSID will be remembered in `/etc/NetworkManager/system-connections` allowing for auto-reconnect after reboot, etc. But if `iwd` is then added to the image, the connection for that remembered SSID will fail after reboot because `iwd` additionally stores the PSK in `/var/lib/iwd` and uses that value rather than the value stored bye NetworkManager. 

So, while `iwd` works great as a backend, the migration would likely be an unpleasant surprise to any user.

**Comment by bsherman** [comment]
> I think we should considerate both independently. There are no timeline nor work in progress right now for `iwd` inclusion so this is about improving the status quo. We can look at the `iwd` transition if and when it happens. We can even consider keeping both in the image and let users make their own choice as `iwd` does not cover 100% use cases from `wpa_supplicant` as far as I remember.

After soliciting feedback from some users, there's pretty clear interest in adding `NetworkManager-wifi`, while `iwd` is less specifically requested.

I do agree, both `wpa_supplicant` and `iwd` could exist on image and user could chose to configure `iwd` if required/desired, but we can still leave that for a separate request.

> Overall it's up to you, but I don't know how would users be expected to manage their wifi interfaces right now on ucore if they don't have this package installed.

Until now, I would assume users have layered packages or built custom images on top of ucore.

**Review by bsherman — APPROVED** [review]

**Pull request merged**
