### PR TITLE
feat: include just/luks rpms from config

### LINKED ISSUE #168: [feat] add a set of images that include ublue-os/config
ujust would be really nice to have on ucore ootb

### PR DESCRIPTION
**Pull request by qoijjj**
closes #168

### CODE REVIEW

**Review by bsherman — COMMENTED** [review]
I commented in the issue #168 so that covers my thoughts regarding the installation of ublue-os-just RPM.

I haven't tested the luks script, but I expect it would work properly on ucore. I'm more agreeable to that package without thinking too deeply about it.

**Comment by bsherman** [comment]
Another thought on luks tpm addition...

We haven't yet done it in ucore, but the main/hwe  ublue-os desktop images rebuild the initramfs as part of image build. We'll want to also rebuild that here to add tpm support else the luks scripts won't work.

see: https://github.com/ublue-os/main/blob/main/initramfs.sh

**Comment by bsherman** [comment]
I did some more digging and I'm very much questioning even the use of the lucks tpm unlock script for ucore. It very much assumes a single encrypted volume based on the default silverblue/kinoite install model, while ucore expects users to use butane/ignition ... and i don't expect a user's encrypted volumes to match the simplicity of a desktop/laptop like that.

Also, after reviewing the ujust recipes, sure there are a couple nice to haves in there, but i don't think they are worth the headache of keeping track of desktop vs coreos appropriate differences and patching to accomodate.

I never expected ucore to share anything with ublue... it just happens that the coreos kernel versions are pinned for use on some desktop images now, so there was opportunity for overlap with kernel and akmods.

I'd prefer if we close this. Thank you for the suggestion.

**Comment by qoijjj** [comment]
@bsherman yeah feel free to close if you don't want it. I was mainly looking for buy-in.

If there isn't any, we'll come up with another solution. Either forking or creating a new intermediate image with ucore as a base

**Pull request closed without merging**
