### PR TITLE
install ZFS from ucore-kmods

### PR DESCRIPTION
**Pull request by bsherman**
This changes ucore image builds such that kmods (zfs) are no longer built in this repo's workflows... instead they are built in https://github.com/ublue-os/ucore-kmods/actions and installed from that repo's resulting image.

### CODE REVIEW

**Comment by ahjohannessen** [comment]
> However, today I'll also be adding a fedora-coreos-zfs image which is stock Fedora CoreOS with one addition, the latest stable ZFS.

Great :) How would I go about using that?

**Comment by bsherman** [comment]
Please take a look at  https://github.com/ublue-os/ucore

The new image which is stock CoreOS+ZFS is listed there, including available tags and how to install.

**Comment by ahjohannessen** [comment]
@bsherman I tried doing
```shell
sudo rpm-ostree --bypass-driver rebase ostree-unverified-registry:ghcr.io/ublue-os/fedora-coreos-zfs:stable
```

Did a reboot and tried `modprobe zfs` - But no zfs.

**Comment by bsherman** [comment]
> Not sure what I did wrong.

oh my! It seems you did it correctly, but I had a copy/paste error in the build workflow.

That has been corrected ( https://github.com/ublue-os/ucore/pull/63 ) and I have verified that `ghcr.io/ublue-os/fedora-coreos-zfs:stable` now contains the ZFS module.

Performing an `rpm-ostree update` on the system should resolve your issue.

Thank you for letting me know about the problem!

**Comment by ahjohannessen** [comment]
zfs installed now :) Do I need to do anything other than: `sudo rpm-ostree --bypass-driver rebase ostree-unverified-registry:ghcr.io/ublue-os/fedora-coreos-zfs:stable` with respect to zincati and otherwise in general?

**Comment by bsherman** [comment]
> @bsherman got zfs working :) Do I need to do anything other than: `sudo rpm-ostree --bypass-driver rebase ostree-unverified-registry:ghcr.io/ublue-os/fedora-coreos-zfs:stable` with respect to zincati and otherwise in general?

1. I've never used `--bypass-driver` so I'm not sure if that is required.

2. Zincati is known to not work with rpm-ostree OCI images... I have an issue tracking the upstream issues here #54 

I do have this noticed in [the repo README](https://github.com/ublue-os/ucore#ucore-1):

> - Disables Zincati auto upgrade/reboot service
>     NOTE: currently, zincati fails to start on systems with OCI based deployments (like uCore). Upstream efforts are active to correct this.
> 

I've tried to keep all major information such as the zincati issue on the README... other than zincati, I'm not aware of any significant differences between rpm-ostree and rpm-ostree native containers.

**Comment by ahjohannessen** [comment]
> I always disable the zincati service.

Interesting. When and how often do you update your CoreOS instances then?

**Comment by bsherman** [comment]
I use the `ucore` image :-)   which ([per the README](https://github.com/ublue-os/ucore#ucore-1)) adds several "nice to have" features, but also:
> Enables staging of automatic system updates via rpm-ostreed

This method is what Fedora Silverblue uses by default ... though our default configuration is to daily download and stage any updates.

It is less refined than zincati, certainly, but one can configure the `rpm-ostreed-automatic.timer` to run weekly and override the service to also reboot by adding an `ExecStartPost=`

Personally, I let my systems stage updates continually, and reboot them manually when desired... But I don't have a large fleet.

**Pull request merged**
